# Generated by Django 3.2.4 on 2021-10-10 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('orderpoint', models.IntegerField(null=True)),
                ('orderquantity', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category_Products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SalePrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channgeddate', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('producttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductType_SalesPrice', to='products.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Producttype_Supplier', to='products.producttype')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supplier_Producttype', to='products.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('upc', models.AutoField(primary_key=True, serialize=False)),
                ('ingressdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('expirationdate', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supplier_GropuProducts', to='products.supplier')),
            ],
        ),
    ]
