# Generated by Django 3.2.4 on 2021-10-13 06:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(max_length=200)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_Supplier', to='products.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('numberoforder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Number_Order', to='products.order')),
                ('producttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_Producttype', to='products.producttype')),
            ],
        ),
    ]
