# Generated by Django 3.2.4 on 2021-09-26 16:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('orderpoint', models.IntegerField()),
                ('reorderpoint', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category_Products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SalePrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channgeddate', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('producttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductType_SalesPrice', to='products.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSuplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Producttype_Suplier', to='products.producttype')),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Suplier_Producttype', to='products.suplier')),
            ],
        ),
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('upc', models.AutoField(primary_key=True, serialize=False)),
                ('ingressdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('expirationdate', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Suplier_GropuProducts', to='products.suplier')),
            ],
        ),
    ]
