# Generated by Django 3.2.4 on 2021-10-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_reorderpoint_producttype_orderquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='orderpoint',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='orderquantity',
            field=models.IntegerField(null=True),
        ),
    ]
