# Generated by Django 3.2.4 on 2021-10-14 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_order_state'),
        ('products', '0003_alter_supplier_email'),
    ]

    operations = [
    ]
