# Generated by Django 3.2.4 on 2021-10-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_20211013_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default='No Enviado', max_length=200),
        ),
    ]
