# Generated by Django 3.2.4 on 2021-10-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_producttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
