# Generated by Django 3.2.4 on 2021-10-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproduct',
            name='producttype',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ProductType_GropuProducts', to='products.producttype'),
            preserve_default=False,
        ),
    ]
