# Generated by Django 3.2.4 on 2021-10-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211014_1424'),
        ('products', '0008_alter_supplier_active'),
    ]

    operations = [
    ]
