# Generated by Django 3.2.4 on 2021-10-19 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_groupproduct_producttype'),
        ('products', '0009_merge_20211016_1538'),
    ]

    operations = [
    ]
