# Generated by Django 3.2.4 on 2021-10-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_order_products_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_products',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
