# Generated by Django 3.2.4 on 2021-10-21 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_merge_20211018_2134'),
        ('products', '0010_merge_20211018_2135'),
        ('products', '0012_alter_order_products_date'),
    ]

    operations = [
    ]
