# Generated by Django 3.2.4 on 2021-10-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_merge_20211021_1716'),
        ('products', '0013_merge_20211021_1724'),
    ]

    operations = [
    ]
