# Generated by Django 3.2.4 on 2021-10-25 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_merge_20211021_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='default_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Default_Supplier', to='products.supplier'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='order_in_progress',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
