# Generated by Django 3.2.4 on 2021-10-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20211009_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nit',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
