# Generated by Django 3.2.4 on 2021-10-16 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_order_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0008_auto_20211009_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sale_Cashier', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sale_Client', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sale_Cashier', to='products.groupproduct')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductSale_Sale', to='clients.sale')),
            ],
        ),
    ]
