# Generated by Django 3.2.4 on 2021-10-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_merge_20211018_2135'),
        ('clients', '0009_productsale_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempProductSale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Temp_Sale_Cashier', to='products.groupproduct')),
            ],
        ),
    ]
